/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { RoastProfile } from "./types";

export function exportRoastToPNG(profile: RoastProfile, isDark: boolean = false) {
  const canvas = document.createElement("canvas");
  canvas.width = 800;
  canvas.height = 550;
  const ctx = canvas.getContext("2d");
  if (!ctx) return;

  // Colors
  const bgColor = isDark ? "#1E1E1B" : "#F7F6F2";
  const textColor = isDark ? "#F0EFEB" : "#111110";
  const subTextColor = isDark ? "#8C8B85" : "#6B6A65";
  const accentColor = isDark ? "#F05A2E" : "#E8441A";
  const borderCol = isDark ? "#2C2C29" : "#E2E1DC";
  const insetColor = isDark ? "#252522" : "#EDEDEA";

  // Draw background
  ctx.fillStyle = bgColor;
  ctx.fillRect(0, 0, canvas.width, canvas.height);

  // Draw thick border
  ctx.strokeStyle = accentColor;
  ctx.lineWidth = 8;
  ctx.strokeRect(0, 0, canvas.width, canvas.height);

  // Draw Header "GITHUB_ROASTER"
  ctx.fillStyle = accentColor;
  ctx.font = "bold 16px monospace";
  ctx.fillText("GITHUB_ROASTER // THE OFFICIAL REPORT CARD", 40, 50);

  // Draw dividing line
  ctx.strokeStyle = borderCol;
  ctx.lineWidth = 1;
  ctx.beginPath();
  ctx.moveTo(40, 70);
  ctx.lineTo(760, 70);
  ctx.stroke();

  // Draw Profile Username & Bio
  ctx.fillStyle = textColor;
  ctx.font = "bold 32px monospace";
  ctx.fillText(`@${profile.username}`, 40, 120);

  ctx.fillStyle = subTextColor;
  ctx.font = "italic 14px Arial";
  // Wrap bio text
  const rawBio = profile.bio || "No bio available.";
  const bioWords = rawBio.length > 70 ? rawBio.slice(0, 67) + "..." : rawBio;
  ctx.fillText(`"${bioWords}"`, 40, 155);

  ctx.fillStyle = subTextColor;
  ctx.font = "bold 12px monospace";
  ctx.fillText(`JOINED ${profile.joinedYear}  ·  ${profile.reposCount} REPOS  ·  ${profile.followersCount} FOLLOWERS`, 40, 195);

  // Draw Grade Badge (Inverted Container on the right side)
  ctx.fillStyle = isDark ? "#161614" : "#111110";
  ctx.fillRect(520, 100, 240, 180);

  // Inner grade square
  ctx.fillStyle = accentColor;
  ctx.fillRect(560, 120, 60, 60);

  ctx.fillStyle = "#FFFFFF";
  ctx.font = "bold 32px monospace";
  ctx.textAlign = "center";
  ctx.fillText(profile.grade, 590, 160);
  ctx.textAlign = "left";

  // Grade Title inside Container
  ctx.fillStyle = "#FFFFFF";
  ctx.font = "bold 15px Arial";
  ctx.fillText(profile.gradeTitle, 560, 210);

  ctx.fillStyle = "#A8A7A2";
  ctx.font = "11px Arial";
  const rawExplanation = profile.gradeExplanation;
  const wrappedExplanation = rawExplanation.length > 30 ? rawExplanation.slice(0, 28) + "..." : rawExplanation;
  ctx.fillText(wrappedExplanation, 560, 235);

  // Segment: Critical Roast Lines
  ctx.fillStyle = textColor;
  ctx.font = "bold 18px monospace";
  ctx.fillText("CRITICAL EVALUATION LATEST //", 40, 260);

  ctx.font = "14px Arial";
  let y = 305;
  profile.roastBullets.slice(0, 4).forEach((bullet: string) => {
    ctx.fillStyle = accentColor;
    ctx.fillText(">", 40, y);
    ctx.fillStyle = textColor;
    
    // Simple text wrapping if bullet is too long
    const text = bullet.length > 62 ? bullet.slice(0, 59) + "..." : bullet;
    ctx.fillText(text, 65, y);
    y += 40;
  });

  // Footer License
  ctx.fillStyle = subTextColor;
  ctx.font = "10px monospace";
  ctx.fillText("THIS REPORT CARD IS COMPUTER-GENERATED BY GITHUB_ROASTER. NO MERCY. ALL RIGHTS ROASTED.", 40, 510);

  // Trigger Download
  const link = document.createElement("a");
  link.download = `github_roast_${profile.username}.png`;
  link.href = canvas.toDataURL("image/png");
  link.click();
}
